### PR TITLE
adds shared workflows

### LINKED ISSUE #6: Add shared workflows

### PR DESCRIPTION
**Pull request by markconroy**
Closes #6 

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by millnut** [comment]
Looks good to me @markconroy can we add an empty `.module` file to stop phpstan complaining it can't find nothing to check. I had to do sinmilar for vacancies https://github.com/localgovdrupal/localgov_job_vacancies/blob/1.x/localgov_job_vacancies.module

**Comment by markconroy** [comment]
empty `.module` is now added.

**Review by millnut — APPROVED** [review]

**Comment by ekes** [comment]
@millnut Is that not an error in PHPStan that wants fixing? `.module` has been optional in Drupal for some time now.

**Comment by millnut** [comment]
> @millnut Is that not an error in PHPStan that wants fixing? `.module` has been optional in Drupal for some time now.

Actually yes thinking about it some more PHPStan expects PHP files or files containing PHP, so we could wrap that step in a check for file types e.g. `.php, .module, .inc, .theme`, etc... and not run that step if it's not present. Let me take a look into in some more in shared workflows, I've created https://github.com/localgovdrupal/localgov_shared_workflows/issues/12 to remind me later

**Pull request merged**
